sanger-pathogens/ariba

- ariba/cluster.py
- ariba/common.py
- setup.py
* Bug fix - when no gene can be chosen because max alignment score = 0, do not try to run an assembly
* increment version number
> Bug fix aln score zero

- .travis.yml
- README.md
- ariba/assembly.py
- ariba/external_progs.py
- ariba/tests/samtools_variants_test.py
- install_dependencies.sh
- setup.py
Initial add of files for Travis. Fingers crossed it works first time...
> Add files for TravisCI

- ariba/card_record.py
- ariba/ref_genes_getter.py
- ariba/tests/card_record_test.py
Try to get just the anitbiotic resistance bit of the name used by CARD at the start of the name output by ariba, so easier to final output files.
> Card rename

- ariba/assembly_variants.py
- ariba/cluster.py
- ariba/summary.py
- ariba/summary_cluster.py
- ariba/tasks/summary.py
- ariba/tests/summary_cluster_test.py
- ariba/versions.py
- delete some files earlier than before to minimise number of files at any one time
- deal with >1 variant in same codon
- summary task: don't make Phandango files if there is only one sample
> Various fixes

- ariba/cluster.py
- ariba/clusters.py
- ariba/common.py
- ariba/tasks/run.py
Adds an option of where to put temporary local assembly files. Careful to delete the temp directory, even when killed by user, or exceptions raised.
> Tmp dir option

- ariba/summary.py
- ariba/tests/summary_test.py
This makes Phandango colours consistent across different runs of summary.
> Phandango colours

- ariba/assembly.py
- ariba/tasks/run.py
- setup.py
Do not use spades --untrusted-contigs option
> Spades not untrusted

- ariba/ref_genes_getter.py
- ariba/tasks/getref.py
Allow the full VFDB to be downloaded as a reference database
> allow full VFDB to be downloaded

- ariba/clusters.py
- ariba/report_filter.py
- ariba/tasks/__init__.py
- ariba/tasks/aln2meta.py
- ariba/tasks/flag.py
- ariba/tasks/getref.py
- ariba/tasks/prepareref.py
- ariba/tasks/refquery.py
- ariba/tasks/reportfilter.py
- ariba/tasks/run.py
- ariba/tasks/summary.py
- ariba/tasks/test.py
- ariba/tasks/version.py
- ariba/tests/report_filter_test.py
- scripts/ariba
Instead of current hacky way of using subcommands, do it properly using argparse
> Use subcommands

- README.md
- ariba/assembly.py
- ariba/clusters.py
- ariba/external_progs.py
- ariba/summary.py
- ariba/tests/assembly_test.py
- scripts/ariba
- setup.py
- clean minimap files
- remove sspace and gapfiller
- fix tree file made by summary, so that phandango can read it (it doesn't like sinlge quotes)
- version bump to 2.0.0 and update readme with new depenencies etc
> Tidy files

- ariba/card_record.py
- ariba/tests/card_record_test.py
- setup.py
> Card 1.1.8

- ariba/mic_plotter.py
- ariba/ref_preparer.py
- ariba/reference_data.py
- ariba/report_filter.py
- ariba/tests/data/ref_preparer_test_run.out/01.filter.check_genes.log
- ariba/tests/data/reference_data_test_remove_bad_genes.log
- ariba/tests/reference_data_test.py
- ariba/tests/report_filter_test.py
- setup.py
- fix y axis label in micplot (should not say "log")
- print warnings to stderr when genes or variants removed by prepareref
- do not filter variants after frameshifts from report.tsv for complete genes
> Reviewer issues

- ariba/ref_genes_getter.py
Hi Martin. I found this line was enough to fix utf-8 encoding issues.
This  + adding curl to the Docker image meant that all database options listed under getref worked for me :)
> Fix utf-8 encoding problems

- ariba/mlst_reporter.py
- ariba/tests/data/mlst_reporter.het_snps.out.details.tsv
- setup.py
This fixes bug with 'hetmin' column of mlst detailed report. It was getting the max instead of min.
> Mlst hetmin bug

- ariba/external_progs.py
- ariba/ref_genes_getter.py
- ariba/tests/data/ref_genes_getter.fix_virulencefinder_fasta_file.in.fa
- ariba/tests/data/ref_genes_getter.fix_virulencefinder_fasta_file.out.fa
- ariba/tests/ref_genes_getter_test.py
- setup.py
* fixed nucmer version detection to work with 3.1 and 4.0
* fix bugs caused by invalid FASTA files from virulencefinder (issue #216)
> virulencefinder and nucmer version fixes

- ariba/assembly.py
- ariba/cdhit.py
- ariba/cluster.py
- ariba/external_progs.py
- ariba/read_filter.py
- ariba/tasks/prepareref.py
- ariba/tasks/run.py
- ariba/tests/assembly_test.py
- ariba/versions.py
- setup.py
Don't warn about spades when it's not being used. Issue #214.
> Remove spades warnings

- ariba/ref_genes_getter.py
- setup.py
See issue #216. Was getting plasmidfinder instead of virulence finder.
> Fix virulencefinder download

- ariba/ref_genes_getter.py
- setup.py
> Resfinder linebreaks

- setup.py
> Remove extra matplotlib entry in install_requires

- CHANGELOG.md
- ariba/ref_genes_getter.py
- setup.py
…nnot method has been updated accordingly
> Fixed GitHub issue #281 - ARG-ANNOT Fails to Download

- ariba/ref_genes_getter.py
Minor change so that the CARD citation message points at the most recent paper.
> Update CARD citation message

- ariba/pubmlst_getter.py
Related to https://github.com/sanger-pathogens/ariba/issues/304
> Fix for changes in PubMLST url

- ariba/ref_genes_getter.py
One solution for fixing CARD downloads with `getref`
> Solution 1: for fixing CARD download
