sanger-pathogens/ariba

ariba/refcheck.py
ariba/tasks/refcheck.py
ariba/tests/data/refcheck_test_check_duplicate_name.fa
ariba/tests/data/refcheck_test_check_spaces_in_name.fa
ariba/tests/refcheck_test.py

When checking if an input sequence was OK, it should have stopped on the first encounter with a sequence that has a space in its name. Instead it carried on. Behaviour was OK when fixing the input sequence, to make a new FASTA file. The PR fixes that bug.

Bug fix: refcheck now dies if spaces in sequence names

---

ariba/tasks/summary.py

This is just a small fix the usage of the script, to stop users using xls files as input instead of tsv.

Clarify usage: input must be tsv, not xls

---

ariba/cluster.py
ariba/common.py
ariba/flag.py
ariba/summary.py
ariba/tasks/summary.py
ariba/tests/cluster_test.py
ariba/tests/flag_test.py
ariba/tests/summary_test.py
setup.py

* New flag 'has_nonsynonymous_variants', so user can easily tell if variants are really change or not
* Extra summary number in summary output, to disinguish between genes that have non-synonymous variants and those that do not
* Option to have summary output all information instead of default, which removes rows or columns where all values are zero (ie gene not there)
* Update dependency versions (which removes numpy as a dependency), and ariba version

Improvements to summary output; new flag for non-synonymous variants

---

ariba/cluster.py
ariba/clusters.py
ariba/common.py
ariba/faidx.py
ariba/mapping.py
ariba/tests/cluster_test.py

- run each cluster in parallel
- changed the output of each cluster to write to its own log file, otherwise all output to stdout is a mess when threads>1
-  SPAdes can fail from spurious mapping causing clusters with only a few reads. When this happens, write a short message to stderr and point the user to a log file containing the output of spades. The old behaviour was intended for debugging and made users think that something really was wrong.

Implement multithreading

---

ariba/assembly_variants.py
ariba/cluster.py
ariba/clusters.py

* when threads == 1, do not use the mlutithreading module. This helps debugging as mluitthreading is stopping getting a proper stack trace.
* Keep flushing log files, so if ariba crashes, at least the log files are up to date.
* When there is >1 indel in a single codon, the code can't yet handle it. This forces a line in the report with 'INDELS' in the variant effect column, so at least we know when it's happening. Should be rare, but utlimately needs handling properly.

One thread not use multithreaded

---

ariba/summary.py
ariba/tasks/summary.py
ariba/tests/data/summary_test_write_phandango_csv.csv
ariba/tests/data/summary_test_write_phandango_files.csv

Make phandango colour evey column consistently

Phandango fix

---

ariba/ref_genes_getter.py
ariba/tasks/run.py

Adds a new option--ref_prefix to the run task. Easier for the user, as don't need to specify all the input files explicitly.

Provide getref prefix to run

---

ariba/clusters.py
ariba/tasks/run.py

- missing files are now written to stderr, instead of stdout.
- fix a typoe in log file saying how ariba was run (the word "run" was missing)

Check all input files exist

---

ariba/__init__.py
ariba/clusters.py
ariba/common.py
ariba/external_progs.py
ariba/ref_preparer.py
ariba/tasks/prepareref.py
ariba/tasks/run.py
ariba/tasks/test.py
ariba/tasks/version.py
ariba/tests/versions_test.py
ariba/versions.py
setup.py

This makes the task "version" report versions of all the dependencies, as well as the ariba version number. Some other tidying up of verbose output.

Report all versions

---

ariba/report.py

This fixes a KeyError when there was no samtools read depth on a contig.

Catch when no coverage from samtools

---

ariba/assembly.py
ariba/cluster.py
ariba/clusters.py
ariba/common.py
ariba/mapping.py
ariba/report_filter.py
ariba/tasks/prepareref.py
ariba/tasks/run.py
ariba/tasks/summary.py
ariba/tests/common_test.py
ariba/tests/data/test_common_cat_files.in.1
ariba/tests/data/test_common_cat_files.in.2
ariba/tests/data/test_common_cat_files.in.3
ariba/tests/data/test_common_cat_files.out
ariba/tests/report_filter_test.py

- clean files asap instead of waiting to the end of each cluster run
- do not write xls files
- keep spades log, warnings and errors
- pull all cluster logs into one final log file
- changed clean option from --clean N to clean everything unless new option --noclean is used
- lower assembly coverage used from 100X to 50X and set -m 4 in spades call

Various fixes

---

ariba/summary.py
ariba/summary_cluster.py
ariba/tasks/summary.py
ariba/tests/summary_cluster_test.py

- bug fix in summary when report had 'MULTIPLE' or "INDELS'.
- add verbose option to summary

Summary inconsistent bug

---

ariba/cluster.py
ariba/clusters.py
ariba/tests/clusters_test.py

Refactoring of code relating to handling signals, errors and cleaning the temp directory. Now tested on lsf and handles hitting mem limit, time limit, bkill.

Tmp dir cleaning

---

ariba/cluster.py

On some OSs, if all jobs were successful, _atexit was getting run on all the clusters, os._exit(1) made it look like they all failed. This stops that behaviour. Still deals with raising errors and signals OK and cleans up temp directory.

Stop returning error when all clusters successful

---

ariba/assembly_variants.py
ariba/report_filter.py
ariba/tasks/reportfilter.py
ariba/tests/assembly_variants_test.py
ariba/tests/report_filter_test.py

Change default behaviour to report all veriants, even for variants-only genes. This makes the only difference between presence/absence and variants-only genes in the summary stage where 'has resistance' is determined.

Always report presabs vars

---

ariba/ext/fml-asm_ariba.cpp
ariba/tests/assembly_test.py

While preparing a Debian package for the 'new' ariba, I noticed that:
- there was still a test that apparently needed a SPAdes installation present, and
- in one of the fermi-lite extension's tests there was a typo in the input file name, leading to failed assertions during the build due to the number of input sequences being zero:
```
test _run_fermilite when it fails ... python3: mrope.c:230: mr_insert_multi: Assertion `len > 0 && s[len-1] == 0' failed.
```
This PR addresses both issues.

Minor fixes

---

README.md
ariba/clusters.py
ariba/external_progs.py
ariba/ref_genes_getter.py
ariba/ref_preparer.py
ariba/report.py
ariba/samtools_variants.py
ariba/summary_cluster.py
ariba/tests/cluster_test.py
ariba/tests/clusters_test.py
ariba/tests/data/clusters_test_write_catted_assemblies_fasta.expected.out.fa
ariba/tests/data/samtools_variants_test_make_vcf_and_read_depths_files.expected.vcf
ariba/tests/ref_preparer_test.py
scripts/ariba
setup.py

Changes:
- report het snps for noncoding sequences
- add plasmidfinder
- write all assemblies to a single file at the end
- better naming of clusters when using argannot
Bug fixes:
- off by one error in ref and contig positions of variants in some report lines
- samtools/bcftools parameters changed for snp calling. Diploid assumption was making some Q scores zero, so got filtered out when they shouldn't have
- cluster naming fixed (was getting broken by vfdb)
- catch when no proper pairs mapped and nothing gets assembled. Writes empty report instead of crashing.

V2.0.0 bug fixes/improvements

---

ariba/ref_genes_getter.py
ariba/summary.py
scripts/ariba

- add srst2_argannot to getref
- remove debug print from summary
- hide --threads, it's causing random errors

Add srst2 argannot

---

ariba/ref_genes_getter.py
ariba/tasks/getref.py
scripts/ariba

Add --version option to getref. Currently only applies to CARD. If not used, gets the latest version.

Add option to choose download version

---

ariba/ref_genes_getter.py
scripts/ariba

add option to download full vfdb, with getref vfdb_full. Previous vfdb download was core, so that is now called vfdb_core instead.

Vfdb get full and core

---

ariba/aln_to_metadata.py
ariba/tasks/aln2meta.py
ariba/tests/aln_to_metadata_test.py
scripts/ariba
setup.py

aln2meta was broken because no need to give a cd-hit cluster representative. This fixes it.

Aln2meta fix

---

ariba/cdhit.py
ariba/reference_data.py
ariba/tests/cdhit_test.py
ariba/tests/data/cdhit_test_run_get_clusters_from_dict_rename.in.fa
ariba/tests/reference_data_test.py
setup.py

Fixes a few bugs relating to contig names and renaming them.

Contig renaming

---

ariba/summary_cluster_variant.py
setup.py

Fixes a bug where in rare cases, there was no samtools call for a variant. Which means the assembly happened, and a variant was called between the assembly and the reference, but samtools had no depth. In the summary file, ARIBA reports ND. This fix handles the case when running ariba summary and ND is in the report file.

bug fix summary when no samtools alt

---

README.md
ariba/summary.py
setup.py

Bug introduced by moving from dendropy 4.1.0 to 4.2.0, where newick tree was defaulting to rooted, putting a '[&R] ' at the start of the tree file, breaking phandango.

Newick rooting bug

---

setup.py

To fix edge case translating coords between contigs and ref sequence (issue #157)

Require pymummer 0.10.2

---

README.md

Added space after codeblock so "Temporary files" subheading renders correctly on github.

Fix bug in README subheading rendering

---

Dockerfile

Docker build has been broken for months. This tests & installs latest ariba release, instead of getting from debian, so we can keep up to date.

Install specific release instead of master branch

---

Dockerfile
ariba/mapping.py
setup.py

Change bowtie2 mapping settings for bowtie2 version >= 2.3.1, not just for ==2.3.1.
Fixes issue #190

Bowtie2 version issues

---

ariba/ref_genes_getter.py

Fairly self explanatory although only lightly tested.

Changed card to utilise .tar.bz2 from .tar.gz

---

ariba/ref_genes_getter.py
scripts/ariba

plasmidfinder, resfinder, and virulencefinder all moved to bitbucket. This changes the behaviour of `getref` to get the tip of master from bitbucket. Alternatively, the user can supply a git commit hash, or "old" to get the old datasets. See issues #216 and #218.

Getref xfinder bitbucket

---

ariba/ref_genes_getter.py
scripts/ariba

Get srst2 argannot version r2 by default. Use `--version r1` to get the old version. Issue #217

Get srst2_argannot latest version r2 by default

---

ariba/assembly.py
ariba/cdhit.py
ariba/cluster.py
ariba/clusters.py
ariba/common.py
ariba/megares_zip_parser.py
ariba/mic_plotter.py
ariba/mlst_reporter.py
ariba/pubmlst_getter.py
ariba/read_filter.py
ariba/ref_genes_getter.py
ariba/ref_preparer.py
ariba/ref_seq_chooser.py
ariba/report_flag_expander.py
ariba/summary_cluster.py
ariba/tests/assembly_test.py
ariba/tests/cluster_test.py
ariba/tests/clusters_test.py
ariba/tests/common_test.py
ariba/tests/megares_zip_parser_test.py
ariba/tests/mic_plotter_test.py
ariba/tests/pubmlst_getter_test.py
ariba/tests/pubmlst_ref_preparer_test.py
ariba/tests/ref_preparer_test.py
ariba/tests/ref_seq_chooser_test.py
ariba/tests/summary_cluster_variant_test.py

Replaces every occurrence of `shutil.rmtree` with a call to `rm -rf`. Hoping this will fix #203 and #205.

Do not use rmtree

---

README.md

Addition of ariba/tb.py itroduced biopython as dependency. Need python >= 3.4 for this.

Update python min version

---

MANIFEST.in

So that they get included in PyPI and Bioconda distributions

Added AUTHORS and LICENSE to the manifest

---

Dockerfile

Changed the docker file to check out latest code from master branch. 
Reconfigured docker hub build to create a versioned image and a "latest" image upon tagging and to create an "unstable" image for master changes.

Removed the specific Ariba release number from the docker file

---

Dockerfile

Added a default locale to fix an encoding error generated from getref for the card database when using docker.

Added default locale to docker file

---

.travis.yml
ariba/megares_zip_parser.py

Fixes issues #287 and #294.
megares changed the filenames and format of their download between versions 1.0.1 and 2.0.0. This PR fixes `ariba getref` so that it works for all available versions (<=2.0.0) of megares at the time of writing.

Handle megares 2.0.0

---

ariba/external_progs.py

This is related to https://github.com/sanger-pathogens/ariba/issues/314
At some point SPAdes changed their `--version` output, causing the warning message from `ariba --version`
```
spades.py --version
SPAdes genome assembler v3.15.2
```
```
ariba version
WARNING: I tried to get the version of spades with: "/home/robert_petit/miniconda3/envs/ariba/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9\.]+)"
ARIBA version: 2.14.6
External dependencies:
bowtie2 2.2.5   /home/robert_petit/miniconda3/envs/ariba/bin/bowtie2
cdhit   4.8.1   /home/robert_petit/miniconda3/envs/ariba/bin/cd-hit-est
nucmer  3.1     /home/robert_petit/miniconda3/envs/ariba/bin/nucmer
spades  ERROR   /home/robert_petit/miniconda3/envs/ariba/bin/spades.py
External dependencies …
```

fix SPAdes version capture

---

ariba/mlst_profile.py
ariba/ref_genes_getter.py

The MLST profile for *Candida glabrata* has a column named `comments` which is not in the ignore list. This PR adds it to the ignore list, as well as drops `Bio.Alphabet` which has been removed in latest Biopython versions.
https://pubmlst.org/bigsdb?db=pubmlst_cglabrata_seqdef&page=downloadProfiles&scheme_id=1
```
ST	FKS	LEU2	NMT1	TRP1	UGP1	URA3	comments
1	7	1	1	6	4	4	
2	1	2	2	1	1	1	
3	5	7	8	7	3	6	
4	7	3	9	8	1	5	
5	5	7	8	1	3	6	
6	2	5	7	5	1	2	
7	3	4	4	3	3	4	
8	1	2	2	1	2	1	
```

Ignore comments column and drop Bio.Alphabet

---

ariba/ref_genes_getter.py

In order to prepare the NCBI acquired gene database, the records that are whole genome as determined by a prefix of 'AP' should be skipped

Skip whole genome records
